### ISSUE TITLE
Spring Boot Learn 6 自定義 多環境配置

### ISSUE THREAD

**Issue by matle970** [matle970/matle970.github.io#40]
Postman:GET
dev:
`http://127.0.0.1:8080/api/v1/books/3`
pro:
`http://127.0.0.1:8081/api/v1/books/3`

開發中會有分好幾個環境，dev開發環境，pro正式環境
1. resource>config>application.yml
2. resource>config>application-dev.yml
3. resource>config>application-pro.yml

- application.yml

```
spring:
  profiles:
    active: pro

book:
  name: 程式入門
  author: 程大詩
  isbn: ${random.uuid}
  description: ${book.name}, 這本書還不賴
```

- application-dev.yml

```
server:
  port: 8080
#  context-path: /api
logging:
  level:
    root: debug
    com.lrm: debug
  file: logs/debug.log

```

- application-pro.yml

```
server:
  port: 8081
#  context-path: /api
logging:
  level:
    root: warn
    com.lrm: info
  file: logs/my.log
```
